---

- name: Check if bk_set.json exists
  ansible.builtin.stat:
    path: "{{ BK_DIR }}/bk-configs/bk_set.json"
  register: bk_set_file_stat

- name: Set HAS_BK_SET_FILE fact
  ansible.builtin.set_fact:
    HAS_BK_SET_FILE: "{{ bk_set_file_stat.stat.exists }}"

- name: Production compose
  ansible.builtin.template:
    src: templates/docker-compose.j2
    dest: "{{ BK_DIR }}/docker-compose.yaml"
    mode: "0644"
  register: compose
  when: not FAST_UPDATE or (UPGRADE is defined and ('compose' in UPGRADE or 'node' in UPGRADE or 'compose-add' in UPGRADE))

- name: Aerospike configuration
  ansible.builtin.template:
    src: templates/aerospike.conf.j2
    dest: "{{ BK_DIR }}/aerospike-config/aerospike.conf"
    mode: "0644"
  register: aerospike
  when: not FAST_UPDATE or (UPGRADE is defined and 'aerospike' in UPGRADE)

- name: Log rotate configuration
  ansible.builtin.template:
    src: templates/logrotate.j2
    dest: "{{ BK_DIR }}/logrotate.sh"
    mode: "0755"
  register: logrotate
  when: not FAST_UPDATE or (UPGRADE is defined and 'logrotate' in UPGRADE)
