---

- name: Compose pull before pre-upgrade stop
  ansible.builtin.shell:
    chdir: "{{ BK_DIR }}"
    cmd: docker compose pull
  when:
    - compose is defined and compose.changed

- name: Node graceful shutdown step 1
  include_tasks: graceful-shutdown.yaml

- name: Node graceful shutdown step 2 (for compose upgrade)
  ansible.builtin.shell:
    chdir: "{{ BK_DIR }}"
    cmd: docker compose down "node{{ NODE_ID }}"
  when:
    - ('compose' in UPGRADE and compose is defined and compose.changed)

- name: Aerospike shutdown for upgrade
  ansible.builtin.shell:
    chdir: "{{ BK_DIR }}"
    cmd: docker compose stop aerospike
  when:
    - ('aerospike' in UPGRADE and aerospike is defined and aerospike.changed)
