---

- name: Graceful shutdown request before stop
  ansible.builtin.shell:
    chdir: "{{ BK_DIR }}"
    cmd: docker compose exec "node{{ NODE_ID }}" pkill node
  ignore_errors: true

- name: Compose stop
  ansible.builtin.shell:
    chdir: "{{ BK_DIR }}"
    cmd: docker compose stop -t {{ STOP_TIMEOUT }}

- name: Compose stop (hard)
  ansible.builtin.shell:
    chdir: "{{ BK_DIR }}"
    cmd: docker compose kill
