---

- name: Graceful shutdown request before stop
  include_tasks: graceful-shutdown.yaml

- name: Compose stop
  ansible.builtin.shell:
    chdir: "{{ BK_DIR }}"
    cmd: docker compose stop

- name: Compose stop (hard)
  ansible.builtin.shell:
    chdir: "{{ BK_DIR }}"
    cmd: docker compose kill
