---

- name: Graceful shutdown request before compose down
  include_tasks: graceful-shutdown.yaml
  when: not DELETE_DATA

- name: Compose stop
  ansible.builtin.shell:
    chdir: "{{ BK_DIR }}"
    cmd: docker compose stop
  ignore_errors: true
  when: not DELETE_DATA

- name: Remove node logs dir
  ansible.builtin.file:
    path: "{{ BK_LOGS_DIR }}"
    state: absent

- name: "Recreate node logs dir exists: {{ BK_LOGS_DIR }}"
  ansible.builtin.file:
    path: "{{ BK_LOGS_DIR }}"
    state: directory
    mode: u=rwx,g=rwx,o=rwx
