---

- name: Fetch Cloudflare IPv4 ranges
  ansible.builtin.uri:
    url: https://www.cloudflare.com/ips-v4
    return_content: true
  register: cf_ips_v4
  delegate_to: localhost
  run_once: true
  become: false
  check_mode: false

- name: Fetch Cloudflare IPv6 ranges
  ansible.builtin.uri:
    url: https://www.cloudflare.com/ips-v6
    return_content: true
  register: cf_ips_v6
  delegate_to: localhost
  run_once: true
  become: false
  check_mode: false

- name: Set Cloudflare IP ranges fact
  ansible.builtin.set_fact:
    cloudflare_ip_ranges: "{{ (cf_ips_v4.content | trim).split('\n') + (cf_ips_v6.content | trim).split('\n') }}"
  run_once: true
  check_mode: false

- name: "Ensures proxy dir exists"
  ansible.builtin.file:
    path: "{{ TLS_PROXY_DIR | mandatory }}/"
    state: directory
    mode: u=rwx,g=r,o=r

- name: "Ensures dir exists: {{ TLS_PROXY_DIR }}/caddy/"
  ansible.builtin.file:
    path: "{{ TLS_PROXY_DIR }}/caddy/"
    state: directory
    mode: u=rwx,g=r,o=r

- name: Copy Dockerfile
  ansible.builtin.template:
    src: templates/Dockerfile.j2
    dest: "{{ TLS_PROXY_DIR }}/Dockerfile"
    mode: "0644"
  register: dockerfile

- name: Production compose
  ansible.builtin.template:
    src: templates/compose.j2
    dest: "{{ TLS_PROXY_DIR }}/compose.yaml"
    mode: "0644"
  register: compose

- name: Copy caddyfile
  ansible.builtin.template:
    src: templates/Caddyfile.j2
    dest: "{{ TLS_PROXY_DIR }}/caddy/Caddyfile"
    mode: "0644"
  register: caddyfile

- name: Copy otel-collector config
  ansible.builtin.template:
    src: templates/otel-collector-config.j2
    dest: "{{ TLS_PROXY_DIR }}/otel-collector-config.yaml"
    mode: "0644"
  register: otelcfg
  when: OTEL_COLLECTOR is defined and OTEL_COLLECTOR | length > 0

- name: Ensure .env
  ansible.builtin.copy:
    dest: "{{ TLS_PROXY_DIR }}/.env"
    content: |
      HOST_PUBLIC_IP={{ HOST_PUBLIC_IP }}
      CADDY_EMAIL={{ CADDY_EMAIL | mandatory }}
    mode: u=rw,g=r,o=r

- name: Copy TLS files
  ansible.builtin.copy:
    dest: "{{ TLS_PROXY_DIR }}/caddy/"
    src: "{{ item }}"
  with_items:
    - "{{ CERT_FILE }}"
    - "{{ CERT_KEY_FILE }}"
  when: ENABLE_GEN_CERT is false and LOAD_CERT is true

- name: Compose up
  ansible.builtin.shell:
    chdir: "{{ TLS_PROXY_DIR }}"
    cmd: docker compose up -d --build --remove-orphans

- name: Restart caddy
  ansible.builtin.shell:
    chdir: "{{ TLS_PROXY_DIR }}"
    cmd: docker compose restart caddy
  when: caddyfile.changed or dockerfile.changed

- name: Restart otel-collector
  ansible.builtin.shell:
    chdir: "{{ TLS_PROXY_DIR }}"
    cmd: docker compose restart otel-collector
  when: otelcfg is defined and otelcfg.changed
