---
THREAD_LOAD_THRESHOLD: 5000
PARALLELIZATION_LEVEL: 20
THREAD_COUNT_SOFT_LIMIT: 16
RAYON_NUM_THREADS: 16
THREAD_LOAD_WINDOW_SIZE: 100
EXT_MESSAGES_TOTAL_LIMIT: 1000 # <- prev. 250 (ext_messages_cache_size)
EXT_MESSAGES_DAPP_LIMIT: 500
EXT_MESSAGES_ACCOUNT_LIMIT: 5
