@port = 8700
@host = http://localhost
@path = v1/send_ext_messages

###

# should get error
POST {{host}}:{{port}}/{{path}} HTTP/1.1
Content-Type: application/json

{}

###

POST {{host}}:{{port}}/{{path}} HTTP/1.1
Content-Type: application/json

{
    "records": [{
        "key": "key1",
        "value": "value1"
    }]
}

###

POST {{host}}:{{port}}/{{path}} HTTP/1.1
Content-Type: application/json

{
    "records": [{
        "key": "key1",
        "value": "value1"
    }, {
        "key": "key2",
        "value": "value2"
    }]
}
