TVCS := SignerIndex BLSKeyIndex BlockKeeperContractRoot AckiNackiBlockKeeperNodeWallet \
		BlockKeeperEpochContract BlockKeeperCoolerContract \
		BlockKeeperPreEpochContract BlockKeeperEpochProxyList \
		License LicenseBM LicenseRoot AckiNackiBlockManagerNodeWallet BlockManagerContractRoot

include ../Makefile.inc
