TVCS := SignerIndex BLSKeyIndex BlockKeeperContractRoot AckiNackiBlockKeeperNodeWallet \
		BlockKeeperEpochContract BlockKeeperCoolerContract \
		BlockKeeperPreEpochContract BlockKeeperEpochProxyList \
		License LicenseRoot

include ../Makefile.inc
